### PR TITLE
Fix async timeout and concurrency issues

### LINKED ISSUE #4: Swell client does not close connection
I'm trying to test the integration with Swell and run into connection errors with jest:

```
 FAIL  test/swell.test.js (5.541 s)
  ✕ should return a list of orders (5044 ms)

  ● should return a list of orders

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      25 | })
      26 | 
    > 27 | test('should return a list of orders', async () => {
         | ^
      28 |   const response = await fastify.inject({
      29 |     method: 'GET',
      30 |     url: '/'

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (test/swell.test.js:27:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.608 s, estimated 7 s
```

this is the file to reproduce the issue easily:

```
const swell = require('swell-node').init(
  process.env.SWELL_ID,
  process.env.SWELL_KEY,
  { cache: false }
)

const fastify = require('fastify')()

fastify.get('/', async function (request, reply) {
  const orders = await swell.get('/orders', {
    limit: 10,
    page: 1
  })
  reply.send(orders)
})

fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})

test('should return a list of orders', async () => {
  const response = await fastify.inject({
    method: 'GET',
    url: '/'
  })
  expect(response.statusCode).toEqual(200)
})
```

### PR DESCRIPTION
**Pull request by PatrickHeneise**
Beside #4, there are also issues when testing multiple requests. Removing bluebird resolves all of those issues.

Closes #4

### CODE REVIEW

File: lib/client.js [hunk 1]
```diff
@@ -118,11 +117,11 @@ Client.prototype.request = function(method, url, data, callback) {
 
   // Resolve data as promised
   const promises = this.promisifyData(data);
+  const that = this
   if (promises.length) {
     return Promise.all(promises)
-      .bind(this)
       .then(() => {
-        this.request(method, url, data, callback);
+        that.request(method, url, data, callback);
```
Comment (ericingram) [inline lib/client.js:124]: @PatrickHeneise can you say, why was this necessary?

Comment (PatrickHeneise) [reply lib/client.js:124]: This replaces Bluebird `.bind(this)` to have "this" context available in the function (Arrow functions do [not have their own bindings to this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).
